spring:
  application:
    name: TrackMyTerm
  data:
    mongodb:
      uri: mongodb+srv://shahvraj2016:MPkGvSaaH0qzBMGr@trackmyterm.mre5b.mongodb.net/?retryWrites=true&w=majority&appName=TrackMyTerm
      database: trackmyterm
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreplytrackmyterm@gmail.com
    password: ohkd mnzy uqlv yxng
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
