spring:
  application:
    name: TrackMyTerm
  data:
    mongodb:
      uri: mongodb+srv://shahvraj2016:MPkGvSaaH0qzBMGr@trackmyterm.mre5b.mongodb.net/?retryWrites=true&w=majority&appName=TrackMyTerm
      database: trackmyterm
